{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "phoenix-app.fullname" . }}-rolebinding
  labels:
    {{- include "phoenix-app.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "phoenix-app.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "phoenix-app.fullname" . }}-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}
