{{- if .Values.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "phoenix-app.fullname" . }}
  labels:
    {{- include "phoenix-app.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.environment }}
  {{- (printf "%s: %s" $key ($value | b64enc)) | nindent 2 }}
  {{- end }}
{{- end }}
